event/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from .forms import EventForm1, EventForm2
from .views import CreateEventWizard



urlpatterns = patterns('event.views',
    url(r'^create_group/$', 'create_group', name='create_group'),
    url(r'^(?P<group_id>\d+)-(?P<group_name>[-\w]+)/', 'group', name='group'),
    url(r'^create_group_event/(?P<group_id>\d+)/$', 'create_group_event', name='create_group_event'),
    url(r'^group_event/(?P<group_event_id>\d+)-(?P<group_event_name>[-\w]+)/', 'group_event', name="group_event"),
    url(r'^create_event/$', login_required(CreateEventWizard.as_view([EventForm1, EventForm2])), name='create_event'),
    url(r'^event/(?P<event_id>\d+)-(?P<event_name>[-\w]+)/', 'event', name='event'),
    url(r'^group_review/(?P<group_id>\d+)/$', 'group_review', name='group_review'),
    url(r'^event_review/(?P<event_id>\d+)/$', 'event_review', name='event_review'),
    url(r'^event_feed/$', 'users_event_feed', name='users_event_feed'),
    url(r'^join_group/(?P<group_id>\d+)/', 'join_group', name="join_group"),
)

powwow/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from home.forms import ContactForm1, ContactForm2
from home.views import ContactWizard
from accounts.forms import UserProfileForm1, UserProfileForm2, UserProfileForm3
from accounts.views import UserCreationWizard

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^event/', include('event.urls', namespace='event', app_name='event')),
    url(r'^notification/', include('Notifications.urls', namespace='notification', app_name='notification')),
    url(r'^friends/', include('Friendships.urls', namespace='friendship', app_name='friendship')),
    url(r'^messages/', include('django_messages.urls')), 
    url(r'^$', 'home.views.home', name="home"),
    url(r'^user/(?P<user_id>\d+)/', 'home.views.users', name="users"),
    url(r'^register/', ('accounts.views.register'), name="register"),
    url(r'^register_confirm/(?P<confirmation_key>\w+)/', ('accounts.views.register_confirm'), name="register_confirm"),
    url(r'^login/', ('accounts.views.login'), name="login"),
    url(r'^logout/', ('accounts.views.logout'), name="logout"),
    url(r'^user_creation/$', login_required(UserCreationWizard.as_view([UserProfileForm1, UserProfileForm2, UserProfileForm3])), name="user_creation"),
    url(r'^contact/$', login_required(ContactWizard.as_view([ContactForm1, ContactForm2])), name='contact'),
    url(r'^about/$', ('home.views.about'), name="about"),
    url(r'^help/$', ('home.views.help'), name="help"),
    
   
)

event/forms.py
from __future__ import absolute_import

from django import forms

from datetimewidget.widgets import DateTimeWidget

from .models import Group, GroupEvent, Event, GroupReview, Review

import datetime
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.layout import Layout
from crispy_forms.bootstrap import TabHolder, Tab

calender_start_date = str(datetime.date.today())
helper = FormHelper()


class GroupForm(forms.ModelForm):
    
    class Meta:
        model = Group
        exclude = ('user', 'pub_date',)
        
        
    
class GroupEventForm(forms.ModelForm):
    class Meta:
        model = GroupEvent
        exclude = ('group', 'location', 'pub_date',)
        
        DateTimeOptions = {
            'format': 'dd/mm/yyyy HH:ii:ss',
			'autoclose': True,
			'startDate': calender_start_date,
        }
        
        widgets = {
            #Use localization and bootstrap 3
            'start_date_and_time': DateTimeWidget(options = DateTimeOptions)
        }
        
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.add_input(Submit('submit', 'Submit'))
        super(GroupEventForm, self).__init__(*args, **kwargs)


class EventForm1(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = ('activity', 'title', 'about', 'thumbnail',)

class EventForm2(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = ('start_date_and_time', 'location', 'address', 'max_people',)
		
        DateTimeOptions = {
            'format': 'dd/mm/yyyy HH:ii:ss',
			'autoclose': True,
			'showMeridian' : True,
			'startDate': calender_start_date,
        }
        
        widgets = {
            #Use localization and bootstrap 3
            'start_date_and_time': DateTimeWidget(options = DateTimeOptions)
        }
        
    

class GroupReviewForm(forms.ModelForm):
    
    class Meta:
        model = GroupReview
        fields = ('rating', 'review',)
    
    def __init__(self, *args, **kwargs):
        super(GroupReviewForm, self).__init__(*args, **kwargs)
        self.fields['rating'].widget.attrs['class'] = 'rating'
        self.fields['rating'].widget.attrs['data-clearable'] = 'remove'
        self.fields['rating'].widget.attrs['data-max'] = '4'
        



class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ('rating', 'review',)
        
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields['rating'].widget.attrs['class'] = 'rating'
        self.fields['rating'].widget.attrs['data-clearable'] = 'remove'
        self.fields['rating'].widget.attrs['data-max'] = '4'
        
        

event/views.py
from __future__ import absolute_import

from django.shortcuts import render, render_to_response
from django.core.urlresolvers import reverse
from django.core.files.storage import default_storage
from django.core.context_processors import csrf
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import get_user_model
from django.contrib.formtools.wizard.views import SessionWizardView
from django.utils.decorators import method_decorator
from django.utils import timezone

from .models import Group, GroupEvent, Event, GroupReview, Review, GroupMember, EventMember, GroupRequest
from .forms import GroupForm, GroupEventForm, GroupReviewForm, ReviewForm
from accounts.models import UserProfile
from Notifications.models import Notifications
from powwow import settings

User = get_user_model()

@login_required
def create_group(request):
    """
    Create a group which user can join. Can be made private.
    """
    email_confirmation = UserProfile.objects.get(user=request.user).email_confirmation
    
    if request.POST:
        form = GroupForm(request.POST, request.FILES)
        
        if form.is_valid():
            save_form = form.save(commit=False)
            save_form.user = request.user
            save_form.pub_date = timezone.now()
            save_form.save()
            
            group_info = Group.objects.get(user=request.user, pub_date=save_form.pub_date)
            name = group_info.title.replace(' ', '-')
            messages.add_message(request, messages.INFO, "The group '%s' was successfully\
             created." % group_info.title)
            
            GroupMember.objects.create(user=request.user, group=group_info)
            
            return HttpResponseRedirect(reverse('event:group', kwargs={
                    'group_id': group_info.id,
                    'group_name': name}))
    
    else:
        form = GroupForm()
    
    args = {}
    args.update(csrf(request))
    args['form'] = form
    
    return render(request, 'create_group.html', args)
        
@login_required
def group(request, group_id, group_name):
    
    rating_list = []
    group_info = Group.objects.get(id=group_id)
    name = UserProfile.objects.get(user=group_info.user)
    group_ratings = GroupReview.objects.filter(group=group_id)
    group_events = GroupEvent.objects.filter(group=group_id)
    
    for ratings in group_ratings:
        rating_list.append(ratings.rating)
        
    if len(rating_list) == 0:
        rating_list.append(1)
    
    args = {}
    args.update(csrf(request))
    args['group_info'] = group_info
    args['name'] = name
    args['average_rating'] = sum(rating_list) // len(rating_list)
    args['events'] = group_events
    
    if group_info.private == True:
        if request.user == group_info.user or GroupMember.objects.get(group=group_id, user=request.user).exists():
            return render(request, 'group.html', args)
        
        else:
            return render(request, 'private_group.html')
    
    return render(request, 'group.html', args)
    

def join_group(request, group_id):
    
    group = Group.objects.get(id=group_id)
    name = group.title.replace(' ', '-')
    
    if GroupMember.objects.filter(group=group, user=request.user).exists() == False:
        if group.private == False:
            GroupRequest.objects.create(
                from_user=request.user,
                to_user=group.user,
                group=group
            )
            messages.add_message(request, messages.SUCCESS, "Group request sent.")
            
            Notifications.objects.create(
                user=group.user,
                message="%s wants to join the group %s." % (request.user.name, group.title)
            )
            
            return HttpResponseRedirect(reverse('event:group', kwargs={
                'group_id': group_id,
                'group_name': name
            }))
            
    
    else:
        return HttpResponseRedirect(reverse('event:group', kwargs={
                'group_id': group_id,
                'group_name': name
            }))
    
        
        
    
    



def create_group_event(request, group_id):

    group_info = Group.objects.get(id=group_id)
    
    if request.user == group_info.user:
        if request.POST:
            form = GroupEventForm(request.POST, request.FILES)
            
            if form.is_valid():
                save_form = form.save(commit=False)
                save_form.pub_date = timezone.now()
                save_form.location = group_info.location
                save_form.group = group_info
                save_form.save()
                
                url_args = GroupEvent.objects.get(group=group_info, pub_date=save_form.pub_date)
                name = url_args.title.replace(' ', '-')
                messages.add_message(request, messages.INFO, "The event '%s' was successfully\
				 created." % url_args.title)
                return HttpResponseRedirect(reverse('event:group_event', kwargs={
                    'group_event_id': url_args.id,
                    'group_event_name': name}))
            
            
	
        else:
            form = GroupEventForm()
            form.helper.form_action = reverse('event:create_group_event', kwargs={'group_id': group_id})
	
        args = {}
        args.update(csrf(request))
        args['form'] = GroupEventForm()
        args['group_info'] = group_info
	
        return render(request, 'create_group_event.html', args)
	
    else:
        return render(request, 'private_group.html')

    
def group_event(request, group_event_id, group_event_name):
    
    event = GroupEvent.objects.get(id=group_event_id)
    
    args = {}
    args.update(csrf(request))
    args['event'] = event
    
    if event.group.private == True:
        if request.user == event.group.user:
            return render(request, 'group_event.html', args)
        
        else:
            return render(request, 'private_group.html')
    
    return render(request, 'group_event.html', args)

        

class CreateEventWizard(SessionWizardView):
    instance = None
    template_name = 'create_event.html'
    file_storage = default_storage

    def get_form_instance( self, step ):
        if self.instance is None:
            self.instance = Event()
        return self.instance

    def done( self, form_list, **kwargs ):
        self.instance.user = self.request.user
        self.instance.pub_date = timezone.now()
        self.instance.save()
        
        url_args = Event.objects.get(user=self.request.user, pub_date=self.instance.pub_date)
        name = url_args.title.replace(' ', '-')
    
        return HttpResponseRedirect(reverse('event:event', kwargs={
            'event_id': url_args.id,
            'event_name': name
            }))

def event(request, event_id, event_name):
    
    event = Event.objects.get(id=event_id)
    
    args = {}
    args.update(csrf(request))
    args['event'] = event
    

    
    return render(request, 'event.html', args)

@login_required
def group_review(request, group_id):

    group_info = Group.objects.get(id=group_id)
    
    if request.user == group_info.user:
        if request.POST:
            form = GroupReviewForm(request.POST)
            if form.is_valid():
                save_form = form.save(commit=False)
                save_form.pub_date = timezone.now()
                save_form.group = group_info
                save_form.user = request.user
                save_form.save()
                
                name = group_info.title.replace(' ', '-')
                messages.add_message(request, messages.INFO, "Your Review has been added.")
                return HttpResponseRedirect(reverse('event:group', kwargs={
                    'group_id': group_id,
                    'group_name': name}))
                    
        else:
            form = GroupReviewForm()
            
	
        args = {}
        args.update(csrf(request))
        args['form'] = form
        args['group_info'] = group_info
	
        return render(request, 'group_review.html', args)
	
    else:
        return render(request, 'private_group.html')
    
    
@login_required
def event_review(request, event_id):
    
    event_info = Event.objects.get(id=event_id)
    
    if request.user == event_info.user:
        if request.POST:
            form = ReviewForm(request.POST)
            if form.is_valid():
                save_form = form.save(commit=False)
                save_form.pub_date = timezone.now()
                save_form.event = event_info
                save_form.user = request.user
                save_form.save()
                
                name = event_info.title.replace(' ', '-')
                messages.add_message(request, messages.INFO, "Your Review has been added.")
                return HttpResponseRedirect(reverse('event:event', kwargs={
                    'event_id': event_id,
                    'event_name': name}))
                    
        else:
            form = ReviewForm()
	
        args = {}
        args.update(csrf(request))
        args['form'] = form
        args['event_info'] = event_info
	
        return render(request, 'review.html', args)
	
    else:
        return render(request, 'private_group.html')
            

@login_required
def users_event_feed(request):
    """
    This method will display activities near to the user's location
    and is interested in.
    
    will also show popular activities in area and most recent in the
    sidebar.
    """
    Interests = []
    user_genres = User.objects.get(id=request.user.id)
    genres = user_genres.interests.all()
    
    for items in genres:
        Interests.append(items)
        
    User_info = UserProfile.objects.get(user=request.user)

event/templates/create_event.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  
  <h2>Create Event</h2>
  <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
  {% for field in form %}
    {{field.error}}

  {% endfor %}
  
  <form action="{% url 'event:create_event' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
  <table>
  {{ wizard.management_form }} <!-- always put this in with wizard form-->
  {% if wizard.form.forms %}
      {{ wizard.form.management_form }}
      {% for form in wizard.form.forms %}
			{{ form|crispy }}
      {% endfor %}
  {% else %}
      {{ wizard.form }}
  {% endif %}
  </table>
  {% if wizard.steps.prev %}
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">"first step"</button>
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">"prev step"</button>
  {% endif %}
  
  
  <input type="submit" value="Submit" />
    
  </form>
  
{% endblock %} 

event/templates/create_group.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-sm-8 blog-main">
	<form action="{% url 'event:create_group' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
		{{ form|crispy }}
		<button class="btn btn-default" type="submit" value="Create">Create</button>
	</form>
</div> 
    

{% endblock %}

event/templates/create_group_event.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-sm-8 blog-main">
	{% crispy form form.helper %}
</div> 
  
{% endblock %} 

event/templates/event.html
{% extends 'base.html' %}



{% block content %}
  
    <h3> {{event.title}} </h3>
    <p> date created <small> {{event.pub_date}} </small></p>
    <p> {{event.about}}<p>
    {% if event.thumbnail %}<img src="/static/assets/{{event.thumbnail}}"/>{% endif %}
    <p> location: {{event.location}}, {{event.address}}</p>
    <p> time: {{event.start_date_and_time}} </p>
    <p> People interested in: {{event.activity}}</p>
    <p>Max people: {{event.max_people}}</p>

{% endblock %}

event/templates/group.html
{% extends 'base.html' %}


{% block content %}
  
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container" style="margin-top: 20px; margin-bottom: 20px;">
	<div class="row panel">
		<div class="col-md-4 bg_blur ">
    	    <a href="{% url 'event:join_group' group_info.id %}" class="follow_btn hidden-xs">Follow</a>
		</div>
        <div class="col-md-8  col-xs-12">
           <img src="/static/assets/{{group_info.thumbnail}}" class="img-thumbnail picture hidden-xs" />
           <img src="http://lorempixel.com/output/people-q-c-100-100-1.jpg" class="img-thumbnail visible-xs picture_mob" />
           <div class="header">
                <h1>{{group_info.title}}</h1>
                <h4><Strong>Organiser: </Strong><a href="{% url 'users' group_info.user.id %}">{{group_info.user.name}}</a></h4>
                <span>{{group_info.about}}</span>
           </div>
        </div>
    </div>   
    
	<div class="row nav">    
        <div class="col-md-4"></div>
        <div class="col-md-8 col-xs-12" style="margin: 0px;padding: 0px;">
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-users fa-lg"></i> 16</div>
            <div class="col-md-4 col-xs-4 well"><i>{% if average_rating == 5 %}<p> <i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i></p>{% endif %}
    {% if average_rating == 4 %}<p> <i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star-empty'></i></p>{% endif %}
    {% if average_rating == 3 %}<p> <i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i></p>{% endif %}
    {% if average_rating == 2 %}<p> <i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i></p>{% endif %}
    {% if average_rating == 1 %}<p> <i class='glyphicon glyphicon-star'></i><i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i></p>{% endif %}
    {% if average_rating == 0 %}<p> <i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i><i class='glyphicon glyphicon-star-empty'></i></p>{% endif %}
   </i> </div>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-comments fa-lg"></i> 26</div>
        </div>
    </div>
</div>

            <!-- Blog Entries Column -->
            <div class="col-md-8">        
                <!-- First Blog Post -->
                <h2>
                   Upcoming Events
                </h2>
                {% if events %}
                
                {% for event in events %}
                <p class="lead">
                    <h4>{{event.title}}</h4>
                </p>
                <p><span class="glyphicon glyphicon-time"></span>{{event.start_date_and_time}}</p>
                <hr>
                <img  src="/static/assets/{{event.thumbnail}}" style="width: 200px; height: 200px">
                <hr>
                <p>{{event.about|truncatewords:30}}</p>

                <hr>
                {% endfor %}
                
                {% else %}
                   <h4>No upcoming events...</h4>
                {% endif %}
                

                
            </div>


            

        </div>
        <!-- /.row -->

        <hr>

    

   
{% endblock %}

event/templates/group_event.html
{% extends 'base.html' %}


{% block content %}
  
    <h3> {{event.title}} </h3>
    <p> date created <small> {{event.pub_date}} </small></p>
    <p> {{event.about}}<p>
    {% if event.thumbnail %}<img src="/static/assets/{{event.thumbnail}}"/>{% endif %}
    <p> location: {{event.location}}, {{event.address}}</p>
    <p> time: {{event.start_date_and_time}} </p>
    <p> People interested in: {{event.activity}}</p>

{% endblock %}

event/templates/group_review.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-sm-8 blog-main">
	<form action="{% url 'event:group_review' group_info.id %}" method="post">{% csrf_token %}
		{{form|crispy}}
		<button class="btn btn-default" type="submit" value="Create">Create</button>
	</form>
</div> 
  
{% endblock %} 

event/templates/private_group.html
{% extends 'base.html' %}

{% block content %}

	<p>This group is private</p>

{% endblock %}

event/templates/review.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-sm-8 blog-main">
	<form action="{% url 'event:event_review' event_info.id %}" method="post">{% csrf_token %}
		{{form|crispy}}
		<button class="btn btn-default" type="submit" value="Create">Create</button>
	</form>
</div> 
  
{% endblock %} 

event/templates/test_form.html
{% extends "base.html" %}
{% load bootstrap_toolkit %}

{% block content %}
  
  <h2>Create Event</h2>
  <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
  {% for field in form %}
    {{field.error}}

  {% endfor %}
  
  <form action="{% url 'event:create_event' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
  <table>
  {{ wizard.management_form }} <!-- always put this in with wizard form-->
  {% if wizard.form.forms %}
      {{ wizard.form.management_form }}
      {% for form in wizard.form.forms %}
          {{ form|as_bootstrap }}
      {% endfor %}
  {% else %}
      {{ wizard.form }}
  {% endif %}
  </table>
  {% if wizard.steps.prev %}
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">"first step"</button>
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">"prev step"</button>
  {% endif %}
  
  
  <input type="submit" value="Submit" />
    
  </form>
  
{% endblock %} 

event/templates/user_event_feed.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
    <div class="row">
    
    {% for event in events %}
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="box">
                <div class="box-icon">
                    <span><img class="img-circle" width="100" height="100" src="/static/assets/{{event.thumbnail}}"/></span>
                </div>
                <div class="info">
                    <h4 class="text-center">{{event.title}}</h4>
                    <p>{{event.about}}</p>
                    <a href="{% url 'event:event' event.id event.title %}" class="btn">See event</a>
                </div>
            </div>
        </div>
        {% endfor %}
	</div>
</div>
{% endblock %}